v1.1.1. Quick color change

diff --git a/sitecopy2 b/sitecopy2
--- a/sitecopy2
+++ b/sitecopy2
@@ -2,7 +2,7 @@
 # Info: Sitecopy 2.0 | Copy site from any environment to Servebolt
 # Date: 6th of October
 # Author: Oskar Voldbakken Hesle
-# Version 1.1
+# Version 1.1.1
 # Dependencies: getopt
 
 pwd="$PWD"
@@ -194,7 +194,7 @@ getConfigFile() {
     printf "\033[1;32mInfo:\033[0m Found more than one remote config file\n\tPlease choose one of the following to set the CMS type with document root and/or getting remote DB credentials:\n"
     local index=
     for index in "${!configArr[@]}"; do
-      printf "\033[1;32m%d\033[0m: \033[34m%s\033[0m\n" "$((index+1))" "${configArr[$index]/$homeDir\//}"
+      printf "\033[1;32m%d\033[0m: \033[1;34m%s\033[0m\n" "$((index+1))" "${configArr[$index]/$homeDir\//}"
     done
 
     num=
@@ -268,7 +268,8 @@ setLocalDBPassword() {
   elif [[ ! "$LOCAL_DBPASS" ]]; then
     # local apiKey=$(awk -F'[=:]' '/api_key/ {print $2}' "$ENV_FILE" | tr -d ' ,"')
     # local envID=$(awk -F'[=:]' '/[^bolt_]id/ {print $2}' "$ENV_FILE" | tr -d ' ,"')
-    printf "\033[1;31mError:\033[0m Updating database password via API is not currently implemented.\nPlease enter local database password for \033[1;34m%s\033[0m: " "$LOCAL_DBNAME" >&2
+    # printf "\033[1;31mError:\033[0m Updating database password via API is not currently implemented.\nPlease enter local database password for \033[1;34m%s\033[0m: " "$LOCAL_DBNAME" >&2
+    printf "Please enter local database password for \033[1;34m%s\033[0m: " "$LOCAL_DBNAME"
     read -s LOCAL_DBPASS
     echo
   fi
