v1.1.5. Cosmetic fixes + cursor fixes for transfer

diff --git a/sitecopy2 b/sitecopy2
--- a/sitecopy2
+++ b/sitecopy2
@@ -2,7 +2,7 @@
 # Info: Sitecopy 2.0 | Copy site from any environment to Servebolt
 # Date: 10th of October, 2023
 # Author: Oskar Voldbakken Hesle
-# Version 1.1.4
+# Version 1.1.5
 # Dependencies: getopt
 
 pwd="$PWD"
@@ -201,7 +201,7 @@ getConfigFile() {
 
   # If more than one config file found, prompt the user for which to use
   if [[ "${#configArr[@]}" -gt 1 ]]; then
-    printf "\033[1;32mInfo:\033[0m Found more than one remote config file\n\tPlease choose one of the following to set the CMS type with document root and/or getting remote DB credentials:\n"
+    printf "\033[1;32mInfo:\033[0m Found more than one remote config file\nPlease choose one of the following to set the CMS type with document root and/or getting remote DB credentials:\n"
     local index=
     for index in "${!configArr[@]}"; do
       printf "\033[1;32m%d\033[0m: \033[1;34m%s\033[0m\n" "$((index+1))" "${configArr[$index]/$homeDir\//}"
@@ -300,7 +300,7 @@ checkDocumentRoot() {
   if [[ "$CONFIG_FILE" == "wp-config.php" ]]; then
     local WPRootDirs=$(ssh -qi "$SSH_PRIVKEY" -p "$SSHPORT" "$SSHUSER@$SSHHOST" "find $CONFIG_PATH -maxdepth 1 -type d \( -name "wp-includes" -o -name "wp-admin" \) -print 2>/dev/null" | wc -l)
 
-    [[ ! "$WPRootDirs" -eq 2 ]] && printf "\033[1;33mWarning:\033[0m Remote document root couldn't be established because of non standard WP structure. Will copy everything as is to destination directory\n" >&2 && return 1
+    [[ ! "$WPRootDirs" -eq 2 ]] && printf "\033[1;33mWarning:\033[0m Remote document root couldn't be established because of non standard WP structure\nWill copy everything as is to destination directory\n" >&2 && return 1
 
     DOCUMENT_ROOT="$CONFIG_PATH"
     LOCAL_CONFIG_PATH=${CONFIG_PATH/$remoteHome/}
@@ -325,7 +325,7 @@ transferFiles() {
 
 transferDatabase() {
   export MYSQL_PWD="$LOCAL_DBPASS"
-  ssh -qi "$SSH_PRIVKEY" -p "$SSHPORT" "$SSHUSER@$SSHHOST" "export MYSQL_PWD='$REMOTE_DBPASS' && mysqldump --single-transaction -u $REMOTE_DBUSER $REMOTE_DBNAME" | pv -ci 0.1 -N"Database Transfer" | sed 's/\sDEFINER=`[^`]*`@`[^`]*`//g' | mysql -u "$LOCAL_DBNAME" "$LOCAL_DBNAME" &
+  ssh -qi "$SSH_PRIVKEY" -p "$SSHPORT" "$SSHUSER@$SSHHOST" "export MYSQL_PWD='$REMOTE_DBPASS' && mysqldump --single-transaction -u $REMOTE_DBUSER $REMOTE_DBNAME" | pv -Wci 0.1 -N"Database Transfer" | sed 's/\sDEFINER=`[^`]*`@`[^`]*`//g' | mysql -u "$LOCAL_DBNAME" "$LOCAL_DBNAME" &
 }
 
 updateLocalConfig() {
@@ -356,16 +356,18 @@ getConfigFile
 [[ ! "$NODB" ]] && setLocalDBPassword
 [[ ! "$NODB" ]] && checkLocalDatabaseConnection
 checkDocumentRoot
+echo
 
 printf "\033[1;32mDoing Transfer...\033[0m\n"
 tput civis
 transferFiles
+sleep .1
 [[ ! "$NODB" ]] && transferDatabase
 wait
 tput cnorm
 
 updateLocalConfig
-printf "\033[1;32mDone!\033[0m\n"
+printf "\033[1;32mDone!\033[0m"
 tput bel
 exit 0
 
